# Generated by Django 5.2.3 on 2025-07-17 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
        migrations.AddField(
            model_name='business',
            name='contact_info',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='saved_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.neighborhood'),
        ),
    ]
