# Generated by Django 5.2.3 on 2025-09-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_helppost_reply_delete_helpexchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='business',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='business',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('retail', 'Retail'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
