# Generated by Django 5.2.3 on 2025-11-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_message_anonymouspost_text_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='anonymouscomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='anonymouspost',
            name='user',
        ),
        migrations.AddField(
            model_name='anonymouspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anonymous_posts/'),
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='created_at',
        ),
    ]
