# Generated by Django 5.2.3 on 2025-11-12 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_postlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouspost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_anonymous_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
